openapi: 3.0.1
info:
  title: '@jupiterone/graph-onelogin'
  description: A JupiterOne managed integration for https://www.onelogin.com
  x-cortex-git:
    github:
      repository: JupiterOne/graph-onelogin
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-onelogin'
  x-cortex-service-groups:
    - tier-4
